### ISSUE TITLE
Feature Request: Foward query parameters (and or path segments) to iFrame

### ISSUE THREAD

**Issue by pReya** [nextcloud/external#479]
It would be very nice, if query parameters were forwarded to the iFrame, so deeplinks/navigational links for the embedded website are still possible.

E.g. a request to `https://cloud.mydomain.de/apps/external/1?page=foo` should attach `?page=foo` to the URL of the external app, so we can still embed specific subpages, etc.

Any security considerations or objections for this feature? I might be able to contribute this myself.

EDIT: The same could work for path segments, too, right? A request to `https://cloud.mydomain.de/apps/external/1/anotherpage` should attach `/anotherpage` to the iFrame `src`.

**Comment by provokateurin** [comment]
I am not sure if this can be implemented correctly. It should be possible to forward the path segments using a fallback parameter that catches everything, but I don't know how this would be possible for query parameters (though there might be a way that I don't know of).

As for security you should be aware that this opens up a way to do redirect attacks. This sounds bad, but it's the same as if the attacker would just redirect you to the embedded page. Not really a new attack vector the attacker wouldn't have already.

I'm wondering a bit what your use case is. Since you can already pass the path segments and query parameters in the settings, what do you want to achieve? In my mind it only makes sense if you plan to redirect users from somewhere else to this embedded site, but then you could instead just redirect them to the original site, right? Maybe I'm missing something here, please enlighten me :)

**Comment by pReya** [comment]
> I'm wondering a bit what your use case is. Since you can already pass the path segments and query parameters in the settings, what do you want to achieve? In my mind it only makes sense if you plan to redirect users from somewhere else to this embedded site, but then you could instead just redirect them to the original site, right? Maybe I'm missing something here, please enlighten me :)

My use case is the following: I use the "external" app, to embed a wiki-like, internal website for users of my instance. I want to link to specific pages inside of this wiki. Of course I can link to these pages outside of my Nextcloud (e.g. via the standalone URL `www.mywiki.com/page1/subpage1`– but then I lose the Nextcloud menu and the single, central URL that I can give out to all my users. I want this thing to stay inside of Nextcloud and still be able to link to a given subpage, which is why I really want to have this feature.

I'll have another look at the code and I'll try to come up with a PR for it.
