### ISSUE TITLE
Ordering, Icons, DropDown, Links

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/external#69]
NC: 12.0.4
External Sites: 2.0.3

- Installed NC and had a few troubles with Instance/my provider so I thought maybe it's an bug I haven't found your app after installing, but it turns out it was just "hidden" in "Additional Settings" and haven't got an extra menu item "External Sites" (like in your screenshot) any longer

- Then I would appreciate a way to change the order of my external sites which is not possible. But there is an App to change the order of menu items ("App Order"), so this is not a problem, but a small hint in the description of this app would be a nice thing.

- In my version is a drop down field for every link element with options "Normal, Setting, Quota". I have no idea what this is about

- I really would like a few more icons (FB, Twitter..) and a way to upload them by administration and links to open in a new window and not as an iframe. This is not possible in my version but it is in your screenshot?! How it comes? Or am I missing something?

**Comment by nickvergessen** [comment]
> haven't got an extra menu item "External Sites" (like in your screenshot) any longer

That is only available in 3.0 and later, so you just need to update to get the extra section

> Then I would appreciate a way to change the order of my external sites which is not possible. But there is an App to change the order of menu items ("App Order"), so this is not a problem, but a small hint in the description of this app would be a nice thing.

Yes, ordering sounds like a nice feature: https://github.com/nextcloud/external/issues/70

> In my version is a drop down field for every link element with options "Normal, Setting, Quota". I have no idea what this is about

That are the 3 spots where the link is displayed. In 3.0 the description of the field was adjusted so this should be better in the future.

> I really would like a few more icons (FB, Twitter..) and a way to upload them by administration and links to open in a new window and not as an iframe. This is not possible in my version but it is in your screenshot?! How it comes? Or am I missing something?

That is because you are running version 2.0 instead of 3.0 of the app. Once you updated to Nextcloud 13 (which is being released soon) you can update to 3.0 and all the features will be available.
